#Database configuration for MySql in Docker
spring:
  datasource:
    url: jdbc:mysql://54.93.233.143:3306/sfgdev
    username: dev_user
    password: password
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false

