#Database configuration for MySql RDS Dev
spring:
  datasource:
    url: jdbc:mysql://sfgdev.c8uy4mhjr2tk.eu-central-1.rds.amazonaws.com/sfgdev
    username: dev_user
    password: password
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false

